### ISSUE TITLE
Deprecated JS

### ISSUE THREAD

**Issue by wellencamass** [hakluke/hakrawler#105]
Hello, Luke!

Could I know why you deprecated the JS crawling functional? 
In my opinion it was a very usefull feature

Also, "these features are written into separate tools that can be piped to from hakrawler" - could you recommend tools which  do JS crawling functional? 

Thanks :)

**Comment by hakluke** [comment]
hey @wellencamass! Check out https://github.com/GerbenJavado/LinkFinder. The regex used to parse paths out of JS files in the original hakrawler was actually taken from that tool.
