### ISSUE TITLE
runtime/internal/sys

### ISSUE THREAD

**Issue by alfonsocaponi** [hakluke/hakrawler#109]
On "Ubuntu 18.04.6 LTS" with "go version go1.17.1 linux/amd64"

using  "go install github.com/hakluke/hakrawler@latest" we have this:

runtime/internal/sys
/usr/local/go/src/runtime/internal/sys/stubs.go:9:7: PtrSize redeclared in this block
	/usr/local/go/src/runtime/internal/sys/arch.go:24:38: previous declaration
/usr/local/go/src/runtime/internal/sys/stubs.go:10:24: undefined: Uintreg
/usr/local/go/src/runtime/internal/sys/stubs.go:16:7: StackGuardMultiplier redeclared in this block
	/usr/local/go/src/runtime/internal/sys/arch.go:27:74: previous declaration

**Comment by hakluke** [comment]
Hey that looks like a problem with your Go installation:

https://stackoverflow.com/questions/62330084/fail-to-build-with-code-go-redeclared-in-this-block
