### ISSUE TITLE
run issue

### ISSUE THREAD

**Issue by alewv** [hakluke/hakrawler#112]
hi,
when i run ~/go/bin/hakrawler 
i get following: 
No urls detected. Hint: cat urls.txt | hakrawler

i don't know what do i wrong. i tried to run it as root/sudo and i still get the same output.
i would appreciate if someone can help. thanks.

**Comment by hakluke** [comment]
Hey!

Check out the hint:

```
cat urls.txt | hakrawler
```

You need to pipe the seed URLs into the tool, for example:

```
echo https://www.google.com | hakrawler
```

**Comment by alewv** [comment]
I pipe the seed urls into the tool like on the example but somehow I am getting these: 
hakrawler: command not found
my go version is: go1.17.3 linux/amd64

**Comment by hakluke** [comment]
Unless you add hakrawler to your $PATH, you will need to specify the full directory. i.e. ~/go/bin/hakrawler

**Comment by alewv** [comment]
got it! thank you so much for your patience and help.
