### ISSUE TITLE
Fails to crawl domains having a port number

### ISSUE THREAD

**Issue by 0xcrypto** [hakluke/hakrawler#113]
Hakrawler fails to crawl the url which have port number mentioned

```
echo "https://hackberry.xyz:443" | hakrawler             # returns no output
```

```
echo "https://hackberry.xyz" | hakrawler                 # works fine
```

**Comment by rmjaadugar** [comment]
+1 no output found for this command too cat alive.txt | hakrawler

**Comment by ErikOwen** [comment]
I think [this commit](https://github.com/hakluke/hakrawler/commit/8b003334484aee78cfcd714a0c5c2077c22e9195) broke the support for specifying port numbers
