### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by herbygillot** [hakluke/hakrawler#114]
Can you specify hakrawler's license?

**Comment by hakluke** [comment]
Why's that? Are you planning on using it in commercial software?

**Comment by herbygillot** [comment]
Nope.  I was looking to add it to [MacPorts](https://www.macports.org/), a package management system for macOS.

**Comment by hakluke** [comment]
Oh cool! I'll look into it!

**Comment by hakluke** [comment]
Done!
