### ISSUE TITLE
Error parsing URL

### ISSUE THREAD

**Issue by 0xKaran** [hakluke/hakrawler#115]
I'm trying to crawl a URL from archive but it shows me an URL parse error

_2021/12/30 02:12:16 Error parsing URL: parse "http://listverse.in:80/info/%3C%=urlKeyword%%3E.html?ses=Y3JlPTEzODY1ODA0OTEmdGNpZD1saXN0dmVyc2UuaW41MmE1OGEwYjljYjZlNi41MDQ4NTE0NSZma2k9NTgzMzg1ODMmdGFzaz1zZWFyY2gmZG9tYWluPWxpc3R2ZXJzZS5pbiZzPWYwZGVjYWUyNzZjMjc1NWUyYjdlJmxhbmd1YWdlPWVuJmFfaWQ9Mg==&keyword=%3C%=urlKeyword%%3E&token=%3C%=token%%3E": invalid URL escape "%=u"_

How to overcome this issue?

**Comment by hakluke** [comment]
The URL is malformed, you need to give hakrawler URLs that are not malformed.
