### ISSUE TITLE
-subs dosent work on kali

### ISSUE THREAD

**Issue by eujas** [hakluke/hakrawler#132]
The -subs apperntly dosent exist, please help

**Comment by Sim4n6** [comment]
Try --subs

**Comment by eujas** [comment]
![Screenshot_20220726-112929_Termius](https://user-images.githubusercontent.com/77516437/180985515-75a92556-1e92-457f-a428-dbbf673eab52.jpg)
Dosent really work

**Comment by hakluke** [comment]
Hey! Apt install on Kali will give you a very old version - try using one of the other install methods 🙂

**Comment by eujas** [comment]
I did that, but it dosent do just subdomains, nothing else
