### ISSUE TITLE
Can we access the urls with .... .com/api

### ISSUE THREAD

**Issue by ninetynin** [hakluke/hakrawler#135]
What I mean is 
For example if there is some website named xyz.com
and lets say im getting js files.... but what i wanna see is the routes of the api of the website xyz.com/api/ but when I use this type of url hakrawler ignores /api/ and just shows xyz.com results...
Is there any way we can try this in hakrawler?

**Comment by ninetynin** [comment]
using this again can we get all urls a website has that are not indexed anywhere? @hakluke

**Comment by hakluke** [comment]
If you're looking for URLs contained within the JavaScript files, this tool won't do it. I'd recommend using hakrawler to discover the JS files, and then use something like https://github.com/xnl-h4ck3r/xnLinkFinder to pull links out of them.
