### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by samokosik** [hakluke/hakrawler#136]
Hello, after running hakrawler using the example above, I get basically zero output.
https://i.imgur.com/I8j1m8C.png
Any tips?

**Comment by samokosik** [comment]
Update: This happens on every version installed via go install. I tried this on kali with apt and everything went fine...

**Comment by hakluke** [comment]
Try it with -subs, or use www.Google.com with the www.

Note that google.com just returns a HTTP redirect.

**Comment by samokosik** [comment]
Yup, -subs option seems to give out needed info. Any way of running it without subs? E.g purely on google.com
It's not a big issue , just wondering

Thank you for assistance

**Comment by hakluke** [comment]
Specify www.Google.com instead of google.com
