### ISSUE TITLE
Hight consume of memory: SSH losing conection.

### ISSUE THREAD

**Issue by GiuBravo** [hakluke/hakrawler#138]
![imagem](https://user-images.githubusercontent.com/7319156/183070560-bfdce96e-a027-4850-9142-82cfa157e385.png)

Command:
```
hakrawler -d 10 -t 100 -subs -u
```
The wordlist used was gerated from httpx and have less then 600 targets.

Today was the fifth time that hakrawler uses all the memory of the machine and I lose the connection with ssh.

**Comment by hakluke** [comment]
This command would probably produce a lot of results - to lower memory consumption you could try not using the -u option as it is not very efficient... instead, just pipe the results to a file, then do a `sort -u` on the file after it is completed.

**Comment by GiuBravo** [comment]
Thanks a lot hakluke! I love your hakrawler! I gonna try it again.

**Comment by hakluke** [comment]
Another way to decrease memory usage of course, is less threads! Let me know how you go!
