### ISSUE TITLE
Regex, status filter support

### ISSUE THREAD

**Issue by SmoZy92** [hakluke/hakrawler#14]
It would be great if the tool supports regex pattern and http status response filtering  !

**Comment by hakluke** [comment]
Hey @SmoZy92,

Thanks for the ticket, can you give more detail about exactly what you mean by this?

Luke

**Comment by hakluke** [comment]
I think @SmoZy92 wants each request to be checked with regex to check for things like secret keys. I think this is a bit out of scope for this tool, which is designed to be a tool to discover endpoints. I think secret discovery would be better suited to a differnt tool which takes the output of hakrawler.
