### ISSUE TITLE
Cannot grab some urls

### ISSUE THREAD

**Issue by anleshared** [hakluke/hakrawler#142]
I think the software is not able to grab urls like this:
<a href="/resetpassword/reset" target="_self">Can’t remember your password?</a>

In this case it should understand that it has to concatenate BASEURL+"resetpassword/reset"

**Comment by hakluke** [comment]
I can't remember if it grabs relative URLs to be honest - but you're probably right. Feel free to make a PR!

**Comment by hakluke** [comment]
I just checked - it grabs relative URLs just fine - the default behaviour is to convert them to absolute URLs before printing.
