### ISSUE TITLE
return nothing.

### ISSUE THREAD

**Issue by OmarJAhmad** [hakluke/hakrawler#145]
hello, i saw the note about the tool that somtimes return nothing,

i have the latest version of hakrawler tool & golang
anyway, 

i have an ip address (login page), when i use gospider tool it return muh results, such as js links, subdomains etc.. it gives more than 300 results, 

when i use hakrawler on the same IP, it return nothing, even when i increase the -d,  or use -subs or even putting the redirected url directly instead of the root path, it still return nothing,

does the tool don't work on IPs ?

![image](https://user-images.githubusercontent.com/42843641/209448902-3fc56a4b-a001-4924-b33b-5c736e98c7a0.png)

thanks in advance

**Comment by hakluke** [comment]
It's tough to know what's going on here without knowing the URL you're
crawling.

**Comment by OmarJAhmad** [comment]
can I send you the URL privately?  via email or something,

thanks.

**Comment by hakluke** [comment]
Yeah you can DM me on Twitter

**Comment by hakluke** [comment]
It was because the SSL certificate wasn't valid for that host... Just needed to use --insecure 🙂
