### ISSUE TITLE
Windows | Error | URL Failed

### ISSUE THREAD

**Issue by ImInTheICU** [hakluke/hakrawler#146]
Im running windows 11, with go for windows.
![Screenshot 2022-12-31 072356](https://user-images.githubusercontent.com/111275373/210138247-0e940cee-ce8a-444a-957f-517a7c2b77a2.png)

**Comment by hakluke** [comment]
Sorry I don't know why this is. Perhaps it has something to do with the way that windows handles line breaks? I've only tested on linux + mac

**Comment by m3hrajbhat** [comment]
> Sorry I don't know why this is. Perhaps it has something to do with the way that windows handles line breaks? I've only tested on linux + mac

Seeing this in linux also!

**Comment by hakluke** [comment]
Are you using the most up to date version? I can't replicate this.

**Comment by m3hrajbhat** [comment]
> Are you using the most up to date version? I can't replicate this.

Yes I believe, I downloaded it via go install github.com/hakluke/hakrawler@latest and using git clone. 
Both throwing same error!

**Comment by AdrianLagartera** [comment]
Same issue with Windows and amd as processor

**Comment by AimanHakeem** [comment]
Issue resolved , need to run using power shell.

**Comment by KalingGo** [comment]
i have the same issue on linux

**Comment by hakluke** [comment]
For others seeing this: it's likely because you don't have a http:// or https:// at the start of the URL.
