### ISSUE TITLE
sudo docker build -t hakluke/hakrawler . sudo docker run --rm -i hakluke/hakrawler --helpCannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running? ERRO[0000] Can't add file /home/teamsync/hakrawler/hakrawler/.git/hooks/push-to-checkout.sample to tar: io: read/write on closed pipe

### ISSUE THREAD

**Issue by TeamSyncOffical** [hakluke/hakrawler#147]
sudo docker build -t hakluke/hakrawler .
sudo docker run --rm -i hakluke/hakrawler --helpCannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
ERRO[0000] Can't add file /home/teamsync/hakrawler/hakrawler/.git/hooks/push-to-checkout.sample to tar: io: read/write on closed pipe

**Comment by hakluke** [comment]
Is the docker daemon running?

**Comment by TeamSyncOffical** [comment]
When i tried running the docker daemon it gave me an error when I get on my virtual machine I will see what the error is.

**Comment by TeamSyncOffical** [comment]
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/teamsync/Dockerfile: no such file or directory

**Comment by hakluke** [comment]
Hey this looks like an issue with the Docker daemon on your machine, not hakrawler.
