### ISSUE TITLE
serve result on browser

### ISSUE THREAD

**Issue by j3rrykh4n** [hakluke/hakrawler#16]
make a server and serve every link there as .html

**Comment by hakluke** [comment]
Sorry I don't understand what you mean, can you elaborate?

**Comment by j3rrykh4n** [comment]
##
package main

import (
    "fmt"
    "net/http"
)

func main() {
    http.HandleFunc("/", HelloServer)
    http.ListenAndServe(":8080", nil)
}

func HelloServer(w http.ResponseWriter, r *http.Request) {
    fmt.print() //thats make a local server and open 8080 port then print your result on browser as html

}
##
You should also ask to help my master
https://github.com/anikhasibul
He is go master😍

**Comment by hakluke** [comment]
Hey again!
Thanks for the ticket but I don't see any benefit to hosting the files discovered locally. The purpose of the tool is simply to gather links from the application.
