### ISSUE TITLE
add basic redirect of input

### ISSUE THREAD

**Issue by marcelo321** [hakluke/hakrawler#164]
`echo https://paypal.com | hakrawler` gives no output.

we need to make it follow the basic redirect for hakrawler to work.. and could be prevented if we just make it follow the initials redirects

```
# curl https://paypal.com -IL
HTTP/2 301 
date: Tue, 17 Sep 2024 23:03:42 GMT
location: https://www.paypal.com/
server: ECAcc (agc/7F3B)
content-length: 0

HTTP/2 302 
server: Varnish
retry-after: 0
location: https://www.paypal.com/us/home
accept-ranges: bytes
date: Tue, 17 Sep 2024 23:03:42 GMT
via: 1.1 varnish
strict-transport-security: max-age=63072000; includeSubDomains; preload
x-served-by: cache-pdk-kfty2130050-PDK
x-cache: HIT
x-cache-hits: 0
server-timing: content-encoding;desc="",x-cdn;desc="fastly"
content-length: 0
```

can we implement this so we don't have to do a curl request before doing hakrawler???

**Comment by marcelo321** [comment]
:(

**Comment by hakluke** [comment]
Hey @marcelo321 - it already does follow redirects. The reason you're isn't providing any output is because it redirects to a different hostname, i.e. paypal.com -> www.paypal.com.

All you need to do is add the `-subs` option to include subdomains, and then it will work.
