### ISSUE TITLE
More Sources

### ISSUE THREAD

**Issue by xyele** [hakluke/hakrawler#21]
I thought you may add other sources like CommonCrawl or OTX.

Also, you may wanna look at this repos.
`https://github.com/xyele/igoturls`
`https://github.com/xyele/secretx` (for extracting API/Secret Keys?)

**Comment by hakluke** [comment]
Hey xyele, it actually does already get commoncrawl and virus total URLs. They're marked as [wayback] with the wayback machine ones, because they all come from the waybackurls code https://github.com/tomnomnom/waybackurls/blob/master/main.go

**Comment by xyele** [comment]
Oh, sorry about that. What about extracting secrets/API's ? (https://github.com/xyele/secretx)
