### ISSUE TITLE
Show Data Source When Using Plain Mode

### ISSUE THREAD

**Issue by ngkogkos** [hakluke/hakrawler#25]
Hello,

When using the `-plain` mode it looks like hakrawler does not show the data source for each link/url found:

![image](https://user-images.githubusercontent.com/1519209/71888235-59aae600-3148-11ea-8bfd-1eb925fa42d1.png)

Worth changing so that it shows the data source with no colors?

**Comment by hakluke** [comment]
hey @ngkogkos :) 

I actually did that on purpose to facilitate easier tool chaining, would you like me to also add in a -nocolour option which omits the banner and colours but keeps the sources?

**Comment by ngkogkos** [comment]
Hi @hakluke.

In terms of bash/text processing, the sources are easier to get rid of with a simple `awk` or `cut` so that users can pipe the output to next tool or a file - compared to color codes always.

You could implement a `-src` flag that shows the data sources, and a `-nocolor` flag for colors. Perhaps another idea is to have a `-outformat` sort of flag which reads multiple flags:

* -outformat CS (Colors and Sources)
* -outformat S (Show data sources only)
* -outformat P (Plain)
* -outformat SP (Plain and data sources)

Overall I think that this is a very minor thing and entirely up to you :), I would add it very much in the bottom of the tasks.

**Comment by hakluke** [comment]
good idea

**Comment by bsysop** [comment]
Its a good option, another crawlers use similar approach.. but also can be done generating json,csv,xml like

```
{[
{
    "type": "url",
    "content": "https://www.sample.com/zxc"
},
{
   ...
}
]}
```

After that user should do some parsing as well, but i think hakrawler do very wide tasks, is almost impossible dont parse something to do some deep work later.

Another possible approach is exports different logs, like

output_js.txt
output_urls.txt

etc, like photon do if i am not wrong.

@hakluke anyways, congratulations dude, i also making my crawler with same ideia, with same lib :), hope we can rock it!

**Comment by hakluke** [comment]
This actually is implemented now - forgot to update here
