### ISSUE TITLE
Add page size limits

### ISSUE THREAD

**Issue by meme-lord** [hakluke/hakrawler#27]
Some sites have massive HTTP downloads (eg ISOs or program installers) that you can't avoid by regexing the URL
When the script follows these URLs it slows down the crawler significantly.
You could perhaps grab the HTTP Headers and check 'Content-Length' before continuing with downloading a page

**Comment by hakluke** [comment]
Hmmm interesting, I'll have to look into how colly handles this. Did you actually strike this problem @meme-lord? I haven't tested it.

**Comment by meme-lord** [comment]
I ran the script on hashkiller.co.uk and I assume its the wordlists on this page that causes it to hang: https://hashkiller.co.uk/Downloads/Wordlists

**Comment by hakluke** [comment]
Yeah that makes sense. Thanks I'll look into it.

**Comment by meme-lord** [comment]
Maybe you can also add a debug switch as well to print out what the script is currently doing (although if there's a lot of multithreading this might not be helpful)

**Comment by garlic0x1** [comment]
> Maybe you can also add a debug switch as well to print out what the script is currently doing (although if there's a lot of multithreading this might not be helpful)

you can use -proxy to debug now

**Comment by hakluke** [comment]
resolved, thanks to @garlic0x1 ! https://github.com/hakluke/hakrawler/pull/122
