### ISSUE TITLE
-urls extract more than urls

### ISSUE THREAD

**Issue by bsysop** [hakluke/hakrawler#29]
When run -urls arg, return also `mailto:` witch are in <a> tag but are not exactly a URL

```
# hakrawler -domain ███████.com -scope subs -depth 1 -plain --urls
https://coach.███████.com/login
mailto:contato@███████.com
```

I think `mailto:` `ftp:` `ssh:` etc, are useful, but not is a url, maybe filter or make another arg to extract all protocols.

What do you think?

PS: I can send the url case in particular, dont want my client found his domain in public repo =]

**Comment by hakluke** [comment]
Hey @bsysop! I did notice this in testing but I'm not really concerned about it, I think including urls with schemas other than http/https is a good thing. If it's breaking tool chaining or something, you can always just pipe it into grep like this:

hakrawler -domain ███████.com -scope subs -depth 1 -plain --urls | grep http

**Comment by bsysop** [comment]
Perfect, thanks @hakluke
