### ISSUE TITLE
Option to set InsecureSkipVerify to true for colly HTTP roundtripper

### ISSUE THREAD

**Issue by daehee** [hakluke/hakrawler#38]
Optional flag `-insecure`, to be able to ignore certificate errors from target urls that cause issues.

```
c.WithTransport(&http.Transport{
		TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
})
```

Reference:
- http://go-colly.org/docs/introduction/configuration/

**Comment by hakluke** [comment]
Thanks to @robre - this is done!
