### ISSUE TITLE
blacklist extentions

### ISSUE THREAD

**Issue by Sy3Omda** [hakluke/hakrawler#42]
Hi,
i was wondering if you could add some blacklist regex for exclude some unnecessary extensions like (jpg|jpeg|gif|css|tif|tiff|png|ttf|woff|woff2|ico) for example.

AND it would be great if this is default whatever i want to go deep using -depth 5 OR 10 even.
i guess no one would need those extensions in terminal output.

Thanks

**Comment by hakluke** [comment]
Hey! Honestly I probably won't ever implement this. You can always just do something like `hakrawler | grep -v -e \.jpg -e \.jpeg -e \.gif` etc.

Additionally, the only time that hakrawler would actually print out one of these file extensions is if there was a link to it directly.
