### ISSUE TITLE
Feature Request: add support for replaying the requests to a proxy

### ISSUE THREAD

**Issue by 0xatul** [hakluke/hakrawler#43]
Something similar to `-replay-proxy` from ffuf making it easy to replay the requests made by the crawler to burp.

**Comment by hakluke** [comment]
Agreed, good shout

**Comment by azimut** [comment]
not ideal but i used https://github.com/hmgle/graftcp without problems

**Comment by hakluke** [comment]
Latest version allows proxy to be specified with `-proxy`, thanks to @garlic0x1
