### ISSUE TITLE
Not working properly

### ISSUE THREAD

**Issue by marcelo321** [hakluke/hakrawler#49]
Hello, i have been using this tool lately but it is not working properly apparently, and also is inconsistent.

Running the following command:

`echo "https://google.com" | hakrawler -plain -depth 3 -scope subs` or
`echo "google.com" | hakrawler -plain -depth 3 -scope subs -wayback`

returns only 272 urls of google, and this is obviously not working properly because it is not getting any subdomains of google and not even a decent amount of directories

**Comment by bsysop** [comment]
Hi @marcelo321 have you tested some another tool in that domain or that tool in another domain?

In some cases that dont will retrieve subs, if main domain dont pointing for these subs.. In google case i would guess they are not pointing for subs.

**Comment by hakluke** [comment]
Hey @marcelo321 - there was a bug which was stopping subdomains from displaying, which means that results from www.google.com (which would be most of them) wouldn't display. Delete the version you have now and download the latest (beta11), and you will find more results :)

**Comment by marcelo321** [comment]
@hakluke do i have to delete the current version to update the tool? doesn't go get github.com.. work?
