### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by sonahri** [hakluke/hakrawler#53]
when i try to go get or try to build it ' this error apears
![Screenshot from 2020-03-31 09 11 15](https://user-images.githubusercontent.com/26815184/77986177-e15f5580-732f-11ea-99fd-e0b3a859962f.png)

**Comment by hakluke** [comment]
Hey @sonahri what version of Golang are you using? Try updating to the latest and doing it again.

**Comment by Nasur0x04** [comment]
@hakluke not work i have lattes version of go same shit

**Comment by hakluke** [comment]
Can you please paste the output of `go version`?]

[image: image.png]

**Comment by 0xsunil** [comment]
Just to make it clear, I updated my go to version `1.13.3` from `1.11`

This avoided all the errors and installation worked perfectly!

**Comment by hakluke** [comment]
I'm going to assume this was the issue!
