### ISSUE TITLE
Max time

### ISSUE THREAD

**Issue by marcelo321** [hakluke/hakrawler#54]
Hello! Would it be possible to add a max time per host?

for example running:

`cat hosts.txt | hakrawler -plain -depth 2 -usewayback -t 20 > out-hakrawler.txt`

meaning that it takes a max time of 20 seconds per host.

**Comment by hakluke** [comment]
Yeah I've actually been thinking about this :)

**Comment by c0d3d-v3n0m** [comment]
You can use the timeout function built into Linux as a workaround:
`timeout 2h hakrawler -url target.com | tee out.txt`

**Comment by hakluke** [comment]
Implemented in the latest version :) you can use `-timeout x` where x is the number of seconds. Thanks to @garlic0x1 for the help!
