### ISSUE TITLE
Feature Request: Show unique URLs

### ISSUE THREAD

**Issue by iqzer0** [hakluke/hakrawler#56]
It would be really great if you could add an option to show unique URL's only. don't show duplicates.

Thank you for this is awesome tool :) kudos to the developers.

**Comment by hakluke** [comment]
Hey @iqzer0 ,

It should be doing this already! Can you give an example where it didn't so I can check it out?

hakluke

**Comment by iqzer0** [comment]
Below is a screenshot.. 

![Screenshot from 2020-04-23 13-55-38](https://user-images.githubusercontent.com/3487952/80079644-ffecf100-8569-11ea-8c44-3d7e4ee75fb5.png)

It would be nice if it can show the output without duplicates by adding a switch like -unique

Sample of expected output
```
~ >>> cat ~/targets/grub.txt|hakrawler -plain -unique

http://phoenix.grab.com/pace.min.js
http://phoenix.grab.com/static/js/app.7ece2191.js
http://eagle.grab.com/static/js/main.56bc84f8.js
http://unicorn.grab.com/pace.min.js
http://unicorn.grab.com/static/js/app.f20e01d7.js
http://watchtower.grab.com/pace.min.js
http://watchtower.grab.com/static/js/app.64b98422.js
http://admiral.grab.com/pace.min.js
http://admiral.grab.com/static/js/app.e80e68df.js
http://jaya.grab.com/pace.min.js
http://jaya.grab.com/static/js/app.724495b9.js
http://stellar.grab.com/static/js/vendor.636307af.chunk.js
http://stellar.grab.com/static/js/main.2b25154a.js
```

**Comment by hakluke** [comment]
Hey @iqzer0,

I can't replicate this behaviour:

```
$ hakrawler -url http://watchtower.grab.com -plain
http://watchtower.grab.com/pace.min.js
http://watchtower.grab.com/static/js/app.cb1985e3.js
```

Is it possible that you have the same URL multiple times in grub.txt in that example?
