### ISSUE TITLE
i got this issue 

### ISSUE THREAD

**Issue by chawdamrunal** [hakluke/hakrawler#59]
# github.com/hakluke/hakrawler/pkg/collector
.go/src/github.com/hakluke/hakrawler/pkg/collector/collector.go:34:23: undefined: strings.ReplaceAll
.go/src/github.com/hakluke/hakrawler/pkg/collector/collector.go:251:23: undefined: strings.ReplaceAll

**Comment by ameenmaali** [comment]
@chawdamrunal it's very likely you are using an old Go version. Update your Go version and it should work.

**Comment by hakluke** [comment]
I assume this fixed it
