### ISSUE TITLE
Doesn't works for some domains?

### ISSUE THREAD

**Issue by SbIm** [hakluke/hakrawler#65]
`hakrawler -url viemo.com` returns nothing but `hakrawler -url google.com` runs well, 

Is this a result of server anti-crawl?

**Comment by bsysop** [comment]
Have tried with vimeo.com?
-- 
*Guillermo Gregorio*
T.: (+55) 34 99124-1302
Skype: b.sword

**Comment by SbIm** [comment]
![Screen Shot 2020-06-28 at 2 14 47 AM](https://user-images.githubusercontent.com/4559937/85929171-2d954400-b8e5-11ea-82a1-3ae8bad35833.png)
Yeah, just like this, no error message as well

**Comment by hakluke** [comment]
This domain works fine for me. Are you sure you're using the most recent version of hakrawler? You can check with `hakrawler -v`. It should be `beta11`.

![image](https://user-images.githubusercontent.com/13975395/85930539-95a55380-b900-11ea-824b-d1830cabb2a0.png)

**Comment by bsysop** [comment]
Probably you have some problems with vimeo

<img width="876" alt="Captura de Tela 2020-06-27 às 16 31 59" src="https://user-images.githubusercontent.com/9998303/85930549-be433400-b893-11ea-9d66-abdd5dcc46f9.png">

try
`curl -i http://vimeo.com`

**Comment by bsysop** [comment]
> This domain works fine for me. Are you sure you're using the most recent version of hakrawler? You can check with `hakrawler -v`. It should be `beta11`.
> 
> ![image](https://user-images.githubusercontent.com/13975395/85930539-95a55380-b900-11ea-824b-d1830cabb2a0.png)

Looks your fingers are milliseconds faster than mine's =]

**Comment by hakluke** [comment]
Dupe! ;)

**Comment by SbIm** [comment]
* `hakrawler -url vimeo.com ` runs well on my local machine but failed on my vps server(kali linux)
* `curl -i http://vimeo.com` works well
*  the version is `beta11`

I'll try to debug it later 😣

**Comment by hakluke** [comment]
I wonder if it could potentially be the golang version? I'm on 1.14, you can check with `go version`

**Comment by SbIm** [comment]
* Update Go version to 1.14.4
* Change my VPS IP address
* Change my VPS location from the US to Singapore

Doesn't work.
Debug the program and I found that `http.Get(robotsURL)` returns a 403 status code, and terminate the program.  
WTF???????
* Go back and check `curl -i http://vimeo.com ` again, yeah there is response but with 403, why I didn't pay any attention at first.
`We detected a high number of errors from your connection. To continue, please confirm that you’re a human (and not a spambot)`
* Open a GUI interface for my VPS, open Vimeo in browser and trigger block, fuck/kill the captcha.
* `hakrawler -url vimeo.com`, works.  

So it's just Vimeo blocked all the IP addresses I've tested...

Thanks for your help!

**Comment by hakluke** [comment]
Glad to hear it's not the tool :)
