### ISSUE TITLE
some js files are not logged

### ISSUE THREAD

**Issue by robre** [hakluke/hakrawler#66]
running `hakrawler -js -url "https://intigriti.com"` doesn't return the scripts that are included in the front-page. Haven't figured out why yet..

**Comment by hakluke** [comment]
Hmm yeah, I just tested the same. That is strange behaviour. Let me know if you figure it out!

**Comment by jsgv** [comment]
Does not return any JS files

**Comment by hakluke** [comment]
Hey! This is fixed in the latest release :)
