### ISSUE TITLE
Feature request: support virtual hosts

### ISSUE THREAD

**Issue by azimut** [hakluke/hakrawler#68]
Setting the Host header doesn't seem to have any effect. Based on other test, might be the flag -headers takes action later.
```
 > strace -s 9999 -f -etrace=write hakrawler -depth 2 -headers 'Host: github.com' -insecure -scope subs -url 140.82.113.4 -plain 2>&1 | grep GET
[pid 22395] write(5, "GET / HTTP/1.1\r\nHost: 140.82.113.4\r\nUser-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36\r\nAccept: */*\r\nAccept-Encoding: gzip\r\n\r\n", 193) = 193
[pid 22395] write(3, "GET /robots.txt HTTP/1.1\r\nHost: 140.82.113.4\r\nUser-Agent: Go-http-client/1.1\r\nAccept-Encoding: gzip\r\n\r\n", 103) = 103
[pid 22396] write(6, "GET /sitemap.xml HTTP/1.1\r\nHost: 140.82.113.4\r\nUser-Agent: Go-http-client/1.1\r\nAccept-Encoding: gzip\r\n\r\n", 104) = 104
```
This particular example works ok as github accepts the host as the ip to later redirect I think.

**Comment by hakluke** [comment]
Ah yeah, nice find. I'll have to look into how to overwrite the Host header.

**Comment by hakluke** [comment]
This is harder than I thought, and it appears it's an issue with Gocolly, see here:

https://github.com/gocolly/colly/issues/564

Once gocolly resolves this I'll be sure to implement it.

**Comment by hakluke** [comment]
A workaround for this is just to add the vhost to your `/etc/hosts` file.

**Comment by ErikOwen** [comment]
I am experiencing this issue as well. I have opened up [this PR](https://github.com/gocolly/colly/pull/691) in gocolly/colly to be able to pass in custom headers (like the `Host` header).
