### ISSUE TITLE
undefined: strings.ReplaceAll

### ISSUE THREAD

**Issue by Th3eCrow** [hakluke/hakrawler#69]
github.com/hakluke/hakrawler/pkg/collector
go/src/github.com/hakluke/hakrawler/pkg/collector/collector.go:34:23: undefined: strings.ReplaceAll
go/src/github.com/hakluke/hakrawler/pkg/collector/collector.go:256:23: undefined: strings.ReplaceAll

**Comment by hakluke** [comment]
You need to update golang :)

**Comment by Th3eCrow** [comment]
Thanks bro its fixed
