### ISSUE TITLE
Error in gocolly

### ISSUE THREAD

**Issue by shubhaparakh** [hakluke/hakrawler#70]
While installing  hakrawler with command:- go get github.com/hakluke/hakrawler

it's giving me the error:-
go/src/github.com/hakluke/hakrawler/pkg/collector/collector.go:15:9: no Go files in /root/go/src/github.com/gocolly/colly

**Comment by JDRanpariya** [comment]
Same here any clue on how to fix that :)

**Comment by geeknik** [comment]
Unable to replicate the issue with Ubuntu 20.04 LTS and go1.15:

```
$ go get github.com/hakluke/hakrawler
go: downloading github.com/hakluke/hakrawler v0.0.0-20200803002250-e39a514d0e17
go: github.com/hakluke/hakrawler upgrade => v0.0.0-20200803002250-e39a514d0e17
$ cat /etc/issue
Ubuntu 20.04.1 LTS \n \l
$ uname -a
Linux sfo2-01 5.4.0-40-generic #44-Ubuntu SMP Tue Jun 23 00:01:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ go version
go version go1.15 linux/amd64
```

**Comment by JDRanpariya** [comment]
> Unable to replicate the issue with Ubuntu 20.04 LTS and go1.15:
> 
> ```
> $ go get github.com/hakluke/hakrawler
> go: downloading github.com/hakluke/hakrawler v0.0.0-20200803002250-e39a514d0e17
> go: github.com/hakluke/hakrawler upgrade => v0.0.0-20200803002250-e39a514d0e17
> $ cat /etc/issue
> Ubuntu 20.04.1 LTS \n \l
> $ uname -a
> Linux sfo2-01 5.4.0-40-generic #44-Ubuntu SMP Tue Jun 23 00:01:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
> $ go version
> go version go1.15 linux/amd64
> ```

Ya, Now I think it got fixed somehow for me I think you can close this issue.
