### ISSUE TITLE
Ouput cannot be saved after "-cookie" flag

### ISSUE THREAD

**Issue by AmanzholZhalynuly** [hakluke/hakrawler#74]
Hi! Thank you for the awesome tool. Lately, I've run into some issues on OS Ubuntu, where I am unable to save the output, but it being displayed on the screen.
The command hakcrawler -url -cookie >> file.txt with cookie being included doesn't save the  output to a file. Although, the comand " hakrawler -url google.com > file.txt " works fine, saving every output to a file. After playing around, it was found that any flag after " -cookie " flag is being ignored.

**Comment by hakluke** [comment]
You need to provide an actual cookie and url in the command. For example:

`hakrawler -url example.com -cookie "session=12345"`

If you just run the command that you put in your issue, you are specifying "-cookie" as the url, and then appending to file.txt, so there won't be any output.

**Comment by AmanzholZhalynuly** [comment]
Here is the full command "hakrawler -url example.com -cookie  _ym_uid=1600266210169246381; _ym_d=1600266210; lang_id=2; lang=kz; _ga=GA1.2.343509312.1600273134; _gid=GA1.2.983303431.1600273134; JSESSIONID=CCF45D9BF9BFE714C2CF02AF846E8F9F; sessionid=CCF45D9BF9BFE714C2CF02AF846E8F9F; >> file.txt. Anything after the cookie flag is ignored

**Comment by hakluke** [comment]
You need to put the cookie in quotes, otherwise bash will interpret each semicolon as a separator between commands

**Comment by AmanzholZhalynuly** [comment]
I'm stupid, thank you :D

**Comment by AmanzholZhalynuly** [comment]
I'm stupid, thank you :D
