### ISSUE TITLE
hakrawler -url https://public-firing-range.appspot.com/ -depth 1 doesn't return anything

### ISSUE THREAD

**Issue by tedmdelacruz** [hakluke/hakrawler#75]
I'm not sure if I'm using hakrawler correctly for this. I tested this against https://public-firing-range.appspot.com/ which contains a simple unordered list:

```html 
<ul>
    <li><a href="/address/index.html">Address DOM XSS</a></li>
    <li><a href="/angular/index.html">Angular-based XSSes</a></li>
    <li><a href="/badscriptimport/index.html">Bad JavaScript imports</a></li>
    <li><a href="/cors/index.html">CORS related vulnerabilities</a></li>
    <li><a href="/dom/index.html">DOM XSS</a></li>
    <li><a href="/escape/index.html">Escaped XSS</a></li>
    <li><a href="/flashinjection/index.html">Flash Injection</a></li>
    <li><a href="/mixedcontent/index.html">Mixed content</a></li>
    <li><a href="/redirect/index.html">Redirect XSS</a></li>
    <li><a href="/reflected/index.html">Reflected XSS</a></li>
    <li><a href="/remoteinclude/index.html">Remote inclusion XSS</a></li>
    <li><a href="/reverseclickjacking/">Reverse ClickJacking</a></li>
    <li><a href="/tags/index.html">Tag based XSS</a></li>
    <li><a href="/urldom/index.html">URL-based DOM XSS</a></li>
    <li><a href="/vulnerablelibraries/index.html">Vulnerable libraries</a></li>
    <li><a href="/leakedcookie/index.html">Leaked httpOnly cookie</a></li>
    <li><a href="/invalidframingconfig/index.html">Invalid framing configuration</a></li>
  </ul>
```

but it doesn't seem to return anything. I'm not sure if I'm missing anything in my usage 😅 

Kudos to @hakluke for this tool, loving it so far! Hoping to contribute soon!

**Comment by hakluke** [comment]
Hey! This is working fine for me, what's the exact command you ran?

![image](https://user-images.githubusercontent.com/13975395/93728096-c1835d00-fc01-11ea-830c-974baf4db44a.png)

**Comment by hakluke** [comment]
Make sure you're using the latest version (beta11 at time of comment).
You can check with `hakrawler -v`

**Comment by tedmdelacruz** [comment]
![1](https://user-images.githubusercontent.com/914090/93728534-e6bc9f00-fbf2-11ea-99a7-d84bc9f3289c.PNG)
hmm, it works with the `-plain` flag 😅 did I find a bug? Can I fix it and push a PR? 😄

**Comment by hakluke** [comment]
It should work without the plain flag too, I just did that for brevity:

![image](https://user-images.githubusercontent.com/13975395/93731544-ce5b7d00-fc10-11ea-8d13-850ce5a15d22.png)

**Comment by tedmdelacruz** [comment]
That's strange, on my end it only returns results with the `-plain` flag. Anyway, using it with the `-plain` flag works for me 👍 cheers!
