### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Aaryan9898** [hakluke/hakrawler#78]
hey whenever i try to run i get this nothing  in output

root@kali:/home/kali/bug-bounty/hakrawler# hawkrawler -url bugcrowd.com -depth 1

██╗  ██╗ █████╗ ██╗  ██╗██████╗  █████╗ ██╗    ██╗██╗     ███████╗██████╗
██║  ██║██╔══██╗██║ ██╔╝██╔══██╗██╔══██╗██║    ██║██║     ██╔════╝██╔══██╗
███████║███████║█████╔╝ ██████╔╝███████║██║ █╗ ██║██║     █████╗  ██████╔╝
██╔══██║██╔══██║██╔═██╗ ██╔══██╗██╔══██║██║███╗██║██║     ██╔══╝  ██╔══██╗
██║  ██║██║  ██║██║  ██╗██║  ██║██║  ██║╚███╔███╔╝███████╗███████╗██║  ██║
╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝ ╚══╝╚══╝ ╚══════╝╚══════╝╚═╝  ╚═╝
                        Crafted with <3 by hakluke                        

it returns nothing as output help  fix it.
i installed it recently and go is working fine.

**Comment by JeffreyShran** [comment]
I have the same problem. I reinstalled hakrawler and golang to make sure.

I don't see a verbose mode to help produce the error but if there's a way then please let me know and I'll be happy to test for you.

Shout if there's any other information that I can provide which will help you to debug.

---------
Versions
---------
GOLANG:- go1.15.3
HAKRAWLER:- beta11
OS:- Debian GNU/Linux 10 (buster) - Linux version 4.19.0-10-amd64

**Comment by hakluke** [comment]
I can't reproduce this on go 1.14, could 1.15 be the issue?

![image](https://user-images.githubusercontent.com/13975395/97080447-bc6d5f80-163e-11eb-82d7-8366235cec07.png)

**Comment by hakluke** [comment]
I also wasn't able to reproduce this on an Ubuntu box running go 1.15.3, latest hakrawler (beta11).

![image](https://user-images.githubusercontent.com/13975395/97080527-6b11a000-163f-11eb-95ae-38d79c1a7d55.png)

My guess is that you hit rate-limiting on bugcrowd.com and got blocked!

**Comment by JeffreyShran** [comment]
Thanks for looking it it. I will do some further testing.

**Comment by Aaryan9898** [comment]
thanks but it still not working in kali linux.

**Comment by JeffreyShran** [comment]
@Aaryan9898 Have you tested on different targets like @hakluke alluded to?

**Comment by hakluke** [comment]
@Aaryan9898 we are going to need more information to figure out what the problem is. What is the version of hakrawler you have installed, and what is the version of Golang you have installed?

**Comment by JeffreyShran** [comment]
@hakluke Confirmed on my side that it was my targets rejecting the requests. I did test on a few domains but they were from the same program so I must have been blocked program-wide. Retested on a non-related site today and no problems. Apologies for taking up your time with this one.

**Comment by Aaryan9898** [comment]
Thanks for reviewing. Liked your speedy response
