### ISSUE TITLE
Customisable depth

### ISSUE THREAD

**Issue by prodigysml** [hakluke/hakrawler#89]
I think this needs to be `depth` instead of `2`, but might be wrong:
https://github.com/hakluke/hakrawler/blob/b72074ea9cff0d1b9d2eaabc5e0b6a2c132c42c0/hakrawler.go#L39

**Comment by prodigysml** [comment]
https://github.com/hakluke/hakrawler/blob/master/hakrawler.go#L34-L39

**Comment by hakluke** [comment]
True that! fixed.
