### ISSUE TITLE
Panic: runtime error: slice bounds out of range [:4116] with capacity 4096

### ISSUE THREAD

**Issue by thezakman** [hakluke/hakrawler#94]
Any idea?

Go version: 
go version go1.16.5 linux/amd64

Panic: runtime error: slice bounds out of range [:4116] with capacity 4096

goroutine 827 [running]:
bufio.(*Writer).Flush(0xc00028a0c0, 0xc00079b2c0, 0x0)
        /usr/local/go/src/bufio/bufio.go:613 +0x1c5
bufio.(*Writer).Write(0xc00028a0c0, 0xc00079b2c0, 0x76, 0x140, 0x1, 0x1, 0x40cd3
b)
        /usr/local/go/src/bufio/bufio.go:643 +0xfc
fmt.Fprintf(0xa49ee0, 0xc00028a0c0, 0x9b607e, 0xa, 0xc0000afce8, 0x1, 0x1, 0xc00
00afcf8, 0x8a14bf, 0x980160)
        /usr/local/go/src/fmt/print.go:205 +0xa5
main.crawl.func1(0xc002d8ecc0)
        /root/go/pkg/mod/github.com/hakluke/hakrawler@v0.0.0-20210705110708-0bd2
b15a7b76/hakrawler.go:70 +0x15a
github.com/gocolly/colly.(*Collector).handleOnHTML.func1(0x257, 0xc002da2750)
        /root/go/pkg/mod/github.com/gocolly/colly@v1.2.0/colly.go:963 +0x8c
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc001461830, 0xc0000afe68, 0x7
)
        /root/go/pkg/mod/github.com/!puerkito!bio/goquery@v1.7.0/iteration.go:10
 +0x53
github.com/gocolly/colly.(*Collector).handleOnHTML(0xc0002889c0, 0xc0002c85c0, 0
x0, 0x0)
        /root/go/pkg/mod/github.com/gocolly/colly@v1.2.0/colly.go:953 +0x2aa
github.com/gocolly/colly.(*Collector).fetch(0xc0002889c0, 0xc00087e100, 0x2f, 0x
9b016b, 0x3, 0x2, 0x0, 0x0, 0xc00038df10, 0xc000799710, ...)
        /root/go/pkg/mod/github.com/gocolly/colly@v1.2.0/colly.go:623 +0x435
created by github.com/gocolly/colly.(*Collector).scrape
        /root/go/pkg/mod/github.com/gocolly/colly@v1.2.0/colly.go:532 +0x3c9

**Comment by hakluke** [comment]
Hey @jub0bs any idea? Looks like it's related to the writer

**Comment by jub0bs** [comment]
@hakluke I'll take a look. I may have inadvertently introduced a race condition. Yikes!

**Comment by jub0bs** [comment]
@thezakman PR #95 should have fixed the issue. Have you been able reproduce it after updating?

**Comment by thezakman** [comment]
I will update today and give it a try, will let you guys know!!

Em dom, 11 de jul de 2021 11:11, jub0bs ***@***.***> escreveu:

**Comment by hakluke** [comment]
LGTM - feel free to open a new issue if you come across anything @thezakman !

**Comment by thezakman** [comment]
It's working like a charm, great tool btw!
