### ISSUE TITLE
Does Hakrawler run in the Mac terminal?

### ISSUE THREAD

**Issue by ngzhiyang** [hakluke/hakrawler#96]
Not sure what the configuration is to run Hakrawler in the Mac terminal. 

I tried opening the file directly, the process immediately ends. If I call upon 'Example usage' nothing happens. 

Managed to change 'hakrawler' to ' ./hakrawler ' when writing commands. haktrails is not found.

Thanks for the help in advance!

**Comment by hakluke** [comment]
Hey! Yes it runs fine on Mac. Try following the installation instructions and then running hakrawler --help

**Comment by ngzhiyang** [comment]
Thanks mate! It required some GO configuration and quick browsing.

In case anyone is looking to configure their MAC, (maybe run the command directly in Terminal) you can use this website https://newbedev.com/where-is-the-zshrc-file-on-mac
